Repository vuejs/vuepress, pull requests merged in 2018-05, with the labels that each got.

#282 feat: generate the timestamp of creation and last updated for each doc file (close #258)
  docs/guide/custom-themes.md
  docs/zh/guide/custom-themes.md
  lib/prepare.js
  lib/util/index.js
  package.json
  yarn.lock
Labels: semver: minor

#405 Remove style override limitation to custom theme
  lib/prepare.js
Labels: 0.9.0

#425 fix: upgrade webpack-serve and avoid port conflict
  lib/dev.js
  package.json
  yarn.lock
Labels: 0.9.0

#438 chore($sidebar): use v-for with key
  lib/default-theme/Sidebar.vue
Labels: 0.9.0

#428 Show OutboundLink icon for external links
  lib/app/app.js
  lib/default-theme/NavLink.vue
  lib/default-theme/NavLinks.vue
  lib/default-theme/Page.vue
  lib/markdown/link.js
Labels: 0.9.0

#379 feat: code line number (close: #365)
  docs/config/README.md
  docs/zh/config/README.md
  lib/default-theme/styles/code.styl
  lib/default-theme/styles/config.styl
  lib/default-theme/styles/theme.styl
  lib/markdown/index.js
  lib/markdown/lineNumbers.js
  lib/markdown/preWrapper.js
Labels: 0.9.0

#480 Core UT
  .babelrc
  .eslintrc.js
  lib/app/app.js
  lib/app/dataMixin.js
  lib/markdown/index.js
  lib/util/index.js
  package.json
  test/app/Content.spec.js
  test/default-theme/DropdownLink.spec.js
  test/default-theme/NavLink.spec.js
  test/default-theme/__snapshots__/DropdownLink.spec.js.snap
  test/default-theme/__snapshots__/NavLink.spec.js.snap
  test/docs-simple/README.md
  test/hoc.js
  test/jest.config.js
  test/markdown/__snapshots__/containers.spec.js.snap
  test/markdown/__snapshots__/highlight.spec.js.snap
  test/markdown/__snapshots__/highlightLines.spec.js.snap
  test/markdown/__snapshots__/hoist.spec.js.snap
  test/markdown/__snapshots__/lineNumers.spec.js.snap
  test/markdown/containers.spec.js
  test/markdown/fragments/code-highlightLines-multiple.md
  test/markdown/fragments/code-highlightLines-single.md
  test/markdown/fragments/code.md
  test/markdown/fragments/container-danger.md
  test/markdown/fragments/container-tip.md
  test/markdown/fragments/container-v-pre.md
  test/markdown/fragments/container-warning.md
  test/markdown/fragments/hoist.md
  test/markdown/highlight.spec.js
  test/markdown/highlightLines.spec.js
  test/markdown/hoist.spec.js
  test/markdown/lineNumers.spec.js
  test/markdown/util.js
  test/prepare.js
  test/util.js
  yarn.lock
Labels: WIP Review

#522 show current page title in front of site title
  lib/app/dataMixin.js
Labels: semver: minor
