Repository vuejs/vuepress, pull requests merged in 2019-03, with the labels that each got.

#1418 feat($plugin-register-components): custom name registration (close: #656)
  packages/@vuepress/plugin-register-components/index.js
  packages/docs/docs/plugin/official/plugin-register-components.md
  packages/docs/docs/zh/plugin/official/plugin-register-components.md
Labels: TBD

#873 fix #849 hero image resizing
  lib/default-theme/Home.vue
Labels: 0.x

#1406 [RFC] plugin-git-log
  rfcs/002.plugin-git-log.md
Labels: RFC

#1464 remove plugin-clean-urls
  packages/@vuepress/plugin-clean-urls/.npmignore
  packages/@vuepress/plugin-clean-urls/README.md
  packages/@vuepress/plugin-clean-urls/index.js
  packages/@vuepress/plugin-clean-urls/package.json
  packages/docs/docs/guide/markdown.md
  packages/docs/docs/plugin/official/plugin-clean-urls.md
  packages/docs/docs/zh/guide/markdown.md
  packages/docs/docs/zh/plugin/official/plugin-clean-urls.md
Labels: semver: patch

#1462 remove plugin-container
  packages/@vuepress/core/lib/node/App.js
  packages/@vuepress/core/package.json
  packages/@vuepress/plugin-container/.npmignore
  packages/@vuepress/plugin-container/README.md
  packages/@vuepress/plugin-container/__tests__/__snapshots__/index.spec.js.snap
  packages/@vuepress/plugin-container/__tests__/fragments/danger.md
  packages/@vuepress/plugin-container/__tests__/fragments/markdown-slots.md
  packages/@vuepress/plugin-container/__tests__/fragments/tip-override.md
  packages/@vuepress/plugin-container/__tests__/fragments/tip.md
  packages/@vuepress/plugin-container/__tests__/fragments/v-pre.md
  packages/@vuepress/plugin-container/__tests__/fragments/warning.md
  packages/@vuepress/plugin-container/__tests__/index.spec.js
  packages/@vuepress/plugin-container/index.js
  packages/@vuepress/plugin-container/package.json
  packages/@vuepress/theme-default/index.js
  packages/@vuepress/theme-default/package.json
  packages/docs/docs/.vuepress/config.js
  packages/docs/docs/guide/markdown.md
  packages/docs/docs/plugin/official/plugin-container.md
  packages/docs/docs/zh/guide/markdown.md
  packages/docs/docs/zh/plugin/official/plugin-container.md
  packages/docs/docs/zh/theme/default-theme-config.md
  packages/docs/docs/zh/theme/using-a-theme.md
  yarn.lock
Labels: semver: patch
